# Google Drive ID of the cards spreadsheet
sheet_gdid: ***

# Sheet type, either "xlsm" (default) or "xlsx"
sheet_type: xlsm

# Local path to the folder with the cropped artwork
artwork_path: C:\Google Drive\Artwork\

# Path to GIMP console executable
gimp_console_path: C:\Program Files\GIMP 2\bin\gimp-console-2.10.exe